name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          🎉 **Welcome to CodeCache!** 🎉

          Thank you for opening your first issue! We're excited to have you contributing to the project.

          Before you get started, please make sure to check out our **contributing guidelines** and **coding standards** to ensure that everything is aligned with the project's workflow. If you have any questions or need help along the way, don't hesitate to ask.

          We appreciate your input and look forward to collaborating with you. 🚀

          Happy coding!
        pr-message: |
          🎉 **Thank you for your first pull request!** 🎉

          We're thrilled to see your contribution to CodeCache. Make sure your code follows the **project guidelines** and has passed all the tests. 

          If you need any assistance or clarification, feel free to ask. We’ll review your PR shortly and provide feedback if needed. Thanks again for helping improve the project!

          Keep up the awesome work! 🚀
